### ISSUE TITLE
[ERROR] No valid path found in `include_dir`!

### ISSUE THREAD

**Issue by sid-verma** [stephenslab/ipynb-website#3] opened 2017-12-31 10:59 UTC
Hi,
I am using the repo without making any changes to it. However when I try building the web pages using `sos-runner ./release.sos -s force`, I get the following error message.

```
INFO: Executing default_1: build ipynb website ...
INFO: input:   []
INFO:
[ERROR] No valid path found in `include_dir`!
Please properly set `include_dir` in `config.yml`.

INFO: output:   []
INFO: Workflow default (ID=383724784dff58c6) is executed successfully.
```

I am not sure if I can ignore the above error, or I am doing something wrong here. Any help is appreciated!

**Comment by pcarbo** [comment] 2018-01-01 19:55
@sidv1993 Thanks for your interest! I was able to reproduce your error. I'm bringing this to the attention of @gaow. It is possible that this is a bug introduced by an update to the SoS program.

**Comment by pcarbo** [comment] 2018-01-04 19:13
@sidv1993 This should be solved by commit 91d382e (version 0.9.2). See [release v0.9.2](https://github.com/stephenslab/ipynb-website/releases/tag/v0.9.2). I'm closing the issue, but please re-open the issue if you are still encountering issues after updating.

**Closed as completed by pcarbo** 2018-01-04 19:13 UTC

**Comment by sidv1993** [comment] 2018-01-07 08:57
@pcarbo I downloaded files from the new commit. Now I see the following message.
```
INFO: Executing default_0:
INFO: input:   []
INFO: output:   []
INFO: Executing default_1: build ipynb website ...
INFO: input:   []
INFO: Executing download-jnbinder:
INFO: input:   []
jnbinder-master.zip: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>:
ERROR: [db0eae5e-3c57-4ec7-81f5-4ad6d7d46f1e]: [download-jnbinder ['jnbinder-master/READ]: RuntimeError: Not all files have been downloaded
[setup-jnbinder]: 1 pending step: setup-jnbinder_0
[default]: 1 pending step: default_2
```
The README.md says that the repo ships with the latest version of jnbinder so am I supposed to run any setup commands before trying to build all the webpages?

**Comment by pcarbo** [comment] 2018-01-08 02:58
@sidv1993 I no longer see your reply on Github.

Did you delete the reply because you solved the issue?

Make sure you have the most recent version of SoS installed, and that you
run "release.sos clean" then "release.sos -s force".

$ sos --version
sos 0.9.10.16

Peter

**Comment by pcarbo** [comment] 2018-01-08 03:03
Ah, nevermind.

I see that you & Gao resolved the issue separately.

Thanks!
Peter

On Sun, Jan 7, 2018 at 8:58 PM, Peter Carbonetto <peter.carbonetto@gmail.com
